### ISSUE TITLE
wikidata query to get all musical instrument

### ISSUE THREAD

**Issue by seansay** [littletouch/instrument-guide#1]
```
SELECT ?s ?desc WHERE {

	?s wdt:P279+ wd:Q34379 .

	OPTIONAL {

		?s rdfs:label ?desc filter (lang(?desc) = "en").

	}

}
````

https://query.wikidata.org/#SELECT%20%3Fs%20%3Fdesc%20WHERE%20%7B%0A%0A%3Fs%20wdt%3AP279%2B%20wd%3AQ34379%20.%0A%0AOPTIONAL%20%7B%0A%0A%3Fs%20rdfs%3Alabel%20%3Fdesc%20filter%20%28lang%28%3Fdesc%29%20%3D%20%22en%22%29.%0A%0A%7D%0A%0A%7D

**Comment by plrthink** [comment]
用上面的 project 的管理进度吧
