### ISSUE TITLE
数据来源问题

### ISSUE THREAD

**Issue by seansay** [littletouch/instrument-guide#3]
现在我们有了接口去获得当前所有乐器的wikidata id，http://okblk9gwp.bkt.clouddn.com/all_ids

客户端应该在第一步fetch这些id。

**Comment by plrthink** [comment]
不是说放到 firebase，从 firebase 获取吗？而且这个也不支持 pagination 吧

**Comment by seansay** [comment]
喔这个issue还没描述完。

这个应该不需要pagination，这个相当于一个全局的乐器id list, 需要客户端第一次初始化请求拿到这个set，存到客户端一个key比如 `ALL_ITEM_IDS`。

我们如果把这个用户已经看过的item的set记做 `READ_ITEM_IDS` （这个就是需要同步到firebase的了，每次修改完需要同步）

每天启动的时候会从 `ALL_ITEM_IDS - READ_ITEM_IDS` 里 random出一个item id（具体的算法可以再看，目前可以简单的随机），拿到id后，请求另一个服务拿到维基百科的内容客户端渲染

**Comment by plrthink** [comment]
ok 懂了

**Comment by seansay** [comment]
已经解决
